from abc import ABC, abstractmethod

class CorpusRepoBase(ABC):
    @abstractmethod
    async def find_by_hash(self, doc_hash: str): ...
    @abstractmethod
    async def upsert_doc(self, record: dict): ...
    @abstractmethod
    async def lsh_query(self, mh_sig: list): ...
    @abstractmethod
    async def near_simhash(self, sh64: int, max_hamming: int = 8): ...
